### ISSUE TITLE
Добавление Toolbar на главный экран

### ISSUE THREAD

**Issue by Komatoz** [KosyanMedia/Aviasales-Android-SDK#1]
Пытаюсь добавить свой тулбар в активити, на котором выводится AviasalesFragment.
Делаю через        mToolbar = (Toolbar) findViewById(R.id.toolbar_actionbar) и т.д., в xml соответственно     через include:
        android:id="@+id/toolbar_actionbar"
        layout="@layout/action_toolbar" 

Проблема в том, что на главной он выводится во-первых серого цвета, во-вторых без заголовка вообще (т.е. на настройки типа   android:background="#3F51B5" в тулбаре или color name="colorAsPrimary" в теме не реагирует). При этом, на поиске  тулбар отображается с заголовками и т.д.

В чем тут может быть дело? Как встроить тулбар на главную и настроить его цветовую гамму?

**Comment by Kpeved** [comment]
Попробуйте не использовать тему AviasalesTemplateTheme.  Она по умолчанию выставляет цвет тулбара как цвет colorAviasalesMain
