### ISSUE TITLE
Виснет поиск в Template 2.0.10

### ISSUE THREAD

**Issue by RankoR** [KosyanMedia/Aviasales-Android-SDK#18]
При поиске (простом) индикатор доходит до конца и ничего не происходит. Ждал около 5 минут.

Параметры:

- Откуда: Москва, любой аэропорт (при выборе конкретного ничего не меняется)
- Куда: Калининград, Питер
- Когда: 25 марта туда, 27 обратно
- Пассажиры: 2 взрослых, 0 остальных.

При смене параметров ничего не меняется, все так же ничего не происходит.

**Comment by Kpeved** [comment]
@RankoR Происходит из-за того что okhttp 3 стал странно обрабатывать кириллицу ( у вас скорее всего название кириллическое) . Поправим в ближайшем релизе.
