### ISSUE TITLE
Where is 2.1.3 repository?

### ISSUE THREAD

**Issue by p-hells** [KosyanMedia/Aviasales-Android-SDK#26]
For example:
```
dependencies {
...
compile 'ru.aviasales.template:aviasalesSdkTemplate:2.1.3-sdk'
...
}
```

I get "Failed to resolve: ru.aviasales.template:aviasalesSdkTemplate:2.1.3-sdk".

`compile 'ru.aviasales.template:aviasalesSdkTemplate:2.1.2-sdk'` is correct.

http://android.aviasales.ru/repositories/ doesn't containt folder 2.1.3-sdk as well (for the template:aviasalesSdkTemplate). 2.1.2-sdk is the latest

**Comment by Kpeved** [comment]
Sorry for that. 2.1.3 was uploaded to our beta repository. Moved to public rep. Should be available right now. Check it out.
