### ISSUE TITLE
template:aviasalesSdkTemplate:2.1.3-sdk gradle issue

### ISSUE THREAD

**Issue by p-hells** [KosyanMedia/Aviasales-Android-SDK#28]
```
dependencies {
 ...
   compile 'ru.aviasales.template:aviasalesSdkTemplate:2.1.3-sdk'
 ...
}
```

Now I get
Error:Failed to resolve: Aviasales-Android-SDK:aviasalesExpandedlistview:unspecified
and
Error:Failed to resolve: Aviasales-Android-SDK:adsinterface:unspecified

**Comment by Kpeved** [comment]
Fixed
