### ISSUE TITLE
template:aviasalesSdkTemplate:1.0.2 does not compile

### ISSUE THREAD

**Issue by armenkh** [KosyanMedia/Aviasales-Android-SDK#3]
Hi Guys,

Adding SDK to Android studio:

dependencies {
..
compile 'ru.aviasales.template:aviasalesSdkTemplate:1.0.2'
}

reports error:

Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find Aviasales-Android-SDK-final:aviasalesExpandedlistview:unspecified.
     Searched in the following locations:
         https://jcenter.bintray.com/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.pom
         https://jcenter.bintray.com/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.jar
         https://repo1.maven.org/maven2/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.pom
         https://repo1.maven.org/maven2/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.jar
         http://android.aviasales.ru/repositories/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.pom
         http://android.aviasales.ru/repositories/Aviasales-Android-SDK-final/aviasalesExpandedlistview/unspecified/aviasalesExpandedlistview-unspecified.jar
         ....

However compile 'ru.aviasales.template:aviasalesSdkTemplate:1.0.1' works fine.

**Comment by RankoR** [comment]
+1 for me. Android Studio 2.0 Preview.
