### ISSUE TITLE
Failed to resolve

### ISSUE THREAD

**Issue by saravanan-vdg** [KosyanMedia/Aviasales-Android-SDK#30]
Error:(29, 13) Failed to resolve: ru.aviasales.template:aviasalesSdk:2.1.3-sdk
<a href="openFile:F:/saravanan/New folder/travel/app/build.gradle">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by Kpeved** [comment]
All working
