### ISSUE TITLE
ADS-free

### ISSUE THREAD

**Issue by maxuna14** [KosyanMedia/Aviasales-Android-SDK#38]
Hi, please add separately ads free version, or make tutorial how to remove all ads integration code.

Thanks

**Comment by maxuna14** [comment]
im not enter appodeal secret key and its ads free, but here is integrated code for this ads, we want fresh code without waste :)

**Comment by Kpeved** [comment]
@maxuna14 There is no current ad-free version of Aviasales SDK . However, we have examples without appodeal libraries - simple_demo & navdrawer_demo.
