### ISSUE TITLE
In class AsAdViewHolder in webView is allways loading url with locale = en

### ISSUE THREAD

**Issue by Kolyall** [KosyanMedia/Aviasales-Android-SDK#39]
In class AsAdViewHolder in webView is allways loading url with locale = en
example of url is 
`http://mobile-ads-content.aviasales.ru/resources/hotellook/sdk.html?source=sdk-backend&token=YOUR_TOKEN&url_scheme=fb643411802345725&geoip_country_code=BY&marker=YOUR_MARKER&adults=1&iata=MSQ&package_name=com.hotellook&currency=usd&search_id=d830452c-3d1b-432c-ab92-5cbced62f486&company_id=230&checkIn=2016-12-22&emplacement=search_results&app_id=YOUR_APP_ID&filter_outlier=1&searchDays=7&nights=8`

after this link  webView loading this one
`http://www.jetradar.com/autocomplete/places?q=MSQ&locale=en`

`locale` is always `en`
See header on attached screenshot
![screenshot31](https://cloud.githubusercontent.com/assets/3495165/21420007/29e84610-c83c-11e6-8850-db04e4d9e321.png)

**Comment by Kpeved** [comment]
We don't run this request implicitly. This is ads banner responsibility.
