### ISSUE TITLE
Failed to resolve: ru.aviasales:aviasalesSdk:2.1.7-sdk 

### ISSUE THREAD

**Issue by caydenliew** [KosyanMedia/Aviasales-Android-SDK#41]
Encounter error when using Gradle:

Error:(40, 13) Failed to resolve: ru.aviasales:aviasalesSdk:2.1.7-sdk

**Comment by kuelye** [comment]
Check [guide](https://github.com/KosyanMedia/Aviasales-Android-SDK#add-gradle-dependencies), you should add custom maven repository `maven { url 'http://android.aviasales.ru/repositories/' }` to `build.gradle`.

**Comment by Flepsik** [comment]
I've done this, but still the same error.
