### ISSUE TITLE
Simple demo returns SERVER_EXCEPTION

### ISSUE THREAD

**Issue by kuelye** [KosyanMedia/Aviasales-Android-SDK#43]
I am trying to run simple demo, but it returns error with 43 error code and 403 response code. Web API is working excellent with my token. I also was trying your SDK with the new application (not your simple demo) and had got same error.

**Comment by Kpeved** [comment]
Hi @kuelye . 
403 is a forbidden message. Probably you don't have permission to use Mobile SDK . Do you have all these marks enabled in your travelpayouts API section ? ( Developers-> Api ) 
<img width="977" alt="screen shot 2017-03-22 at 11 01 55 am" src="https://cloud.githubusercontent.com/assets/8842917/24187804/adc95600-0eef-11e7-888d-ad7df1a07144.png">
