### ISSUE TITLE
failed to resolve sdk

### ISSUE THREAD

**Issue by Flepsik** [KosyanMedia/Aviasales-Android-SDK#44]
`Error:(52, 13) Failed to resolve: ru.aviasales:aviasalesSdk:2.1.3-sdk`
same with 2.1.7 version

I didn't miss ` maven { url 'http://android.aviasales.ru/repositories/' }`
Your demo project doesn't compile too. 
Maybe something's wrong with repository?

**Comment by Kpeved** [comment]
Thank you for this issue @Flepsik . Should work right now.
