### ISSUE TITLE
Need help with SDK_HOST

### ISSUE THREAD

**Issue by vishalvijay** [KosyanMedia/Aviasales-Android-SDK#56]
Hi

I upgraded the SDK from 2.1.7 to 2.1.10.
Changes made 
```
AviasalesSDK.getInstance().init(this, new IdentificationData(TRAVEL_PAYOUTS_MARKER, ADDITIONAL_MARKER, TRAVEL_PAYOUTS_TOKEN));
```
=>
```
AviasalesSDK.getInstance().init(this, new SdkConfig(TRAVEL_PAYOUTS_MARKER, TRAVEL_PAYOUTS_TOKEN, TRAVEL_PAYOUTS_SDK_HOST, ADDITIONAL_MARKER));
```

I tried setting `TRAVEL_PAYOUTS_SDK_HOST` to my whitelable but it didn't work so tried with `http://www.travel-api.pw/`, that too didn't work. (Airport search API itself not working, never ending)

Any help? (Is there any other changes I need to make when upgrading from 2.1.7 to 2.1.10)

**Comment by vishalvijay** [comment]
It worked when I changed `http://www.travel-api.pw/` => `www.travel-api.pw`

Thanks

**Comment by Kpeved** [comment]
Hi @vishalvijay 
No, adding SDK_HOST  is enough. It should work. 
What exactly is the value of your TRAVEL_PAYOUTS_SDK_HOST?  It shouldn't contain "http://" part. 
It has to be just "www.travel-api.pw". 
Could you please try it?

**Comment by Kpeved** [comment]
Great, you figured it out :)
