### ISSUE TITLE
deprecated ActionBarActivity class is used in SDK

### ISSUE THREAD

**Issue by armenkh** [KosyanMedia/Aviasales-Android-SDK#6]
Deprecated  ActionBarActivity is used in class BaseFragment:

protected ActionBar getActionBar() {
        return ((ActionBarActivity)this.getActivity()).getSupportActionBar();
 }

AppCompatActivity should be used instead.

**Comment by RankoR** [comment]
Плюсую. Не можем нормально интегрировать SDK, т.к. у нас AppCompat везде.

**Comment by Kpeved** [comment]
в 2.0.8 перешли на AppCompatActivity
