### ISSUE TITLE
Error:Failed to resolve: Aviasales-Android-SDK-final:aviasalesExpandedlistview:unspecified

### ISSUE THREAD

**Issue by StanislavZakharov** [KosyanMedia/Aviasales-Android-SDK#8]
Ваша библиотека не синхронизируется с gradle. Пишит следующую ошибку:

Error:Failed to resolve: Aviasales-Android-SDK-final:aviasalesExpandedlistview:unspecified

**Comment by Kpeved** [comment]
В 2.0.8 уже поправлено
